# Generated by Django 3.0.4 on 2020-04-16 09:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=150)),
                ('semester', models.IntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Third Semester'), (4, 'Fourth Semester'), (5, 'Fifth Semester'), (6, 'Sixth Semester'), (7, 'Seventh Semester'), (8, 'Eighth Semester'), (0, 'Department Electives')])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date_mdy', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReviewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(blank=True, max_length=150, null=True)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('course_instructor', models.CharField(max_length=150)),
                ('session', models.CharField(max_length=20)),
                ('grade_awarded', models.CharField(max_length=2)),
                ('course_difficulty', models.CharField(max_length=20)),
                ('pre_requisites', models.CharField(max_length=150)),
                ('assesments_methods', models.TextField()),
                ('topics_covered', models.TextField()),
                ('weightage', models.TextField()),
                ('lecture_lab_review', models.TextField()),
                ('exam_review', models.TextField()),
                ('performance_tips', models.TextField()),
                ('references', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Course')),
            ],
        ),
    ]
