# Generated by Django 3.0.4 on 2020-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewdata',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
