# Generated by Django 3.0.4 on 2020-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20200416_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewdata',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
