# Generated by Django 3.0.4 on 2020-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20200416_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereviewdata',
            name='attendance_policy',
            field=models.CharField(default='80% attendace is required officially', max_length=150),
        ),
    ]
