# Generated by Django 3.0.4 on 2020-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_coursereviewdata_attendance_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eighth', 'Eighth'), ('elective', 'Elective')], default='elective', max_length=20, verbose_name='Semester'),
        ),
    ]
