# Generated by Django 3.0.4 on 2020-04-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200425_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewdata',
            name='course_difficulty',
            field=models.CharField(choices=[('very-easy', 'Very-Easy'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('very-difficult', 'Very-Difficult')], default='moderate', max_length=20, verbose_name='Difficulty'),
        ),
    ]
