# Generated by Django 3.0.4 on 2020-04-09 06:34

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20200409_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date_mdy',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
