# Generated by Django 3.0.4 on 2020-04-25 11:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20200425_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewdata',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='course', unique=True),
        ),
    ]
