# Generated by Django 3.0.4 on 2020-04-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20200425_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewdata',
            name='pre_requisites',
            field=models.CharField(max_length=300),
        ),
    ]
