# Generated by Django 3.0.4 on 2020-04-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20200414_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReviewData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(blank=True, max_length=150, null=True)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('course_instructor', models.CharField(max_length=150)),
                ('grade_awarded', models.CharField(max_length=2)),
                ('course_difficulty', models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Moderate'), ('4', 'Difficult'), ('5', 'Very Difficult')], max_length=2)),
                ('pre_requisites', models.CharField(max_length=150)),
                ('assesments_methods', models.TextField()),
                ('topics_covered', models.TextField()),
                ('weightage', models.TextField()),
                ('lecture_lab_review', models.TextField()),
                ('exam_review', models.TextField()),
                ('performance_tips', models.TextField()),
                ('references', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Course')),
            ],
        ),
    ]
