# Generated by Django 3.0.4 on 2020-04-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_coursereviewdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviewdata',
            name='course_difficulty',
            field=models.CharField(max_length=20),
        ),
    ]
